[project]
name = "ece-big-data-2026-2027"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "e-menut-ece", email = "edouardmenut04@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.5.6",
    "faker>=40.37.0",
]

[project.scripts]
dataset-users = "ece_big_data_2026_2027.dataset_users:main"
dataset-orders = "ece_big_data_2026_2027.dataset_orders:main"
orders-report = "ece_big_data_2026_2027.orders_report:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
